title: Home
baseurl: "" # Jangan lupa isi jika repo bukan user/organization site
url: "https://muhammadalfaraby06.github.io"

sass:
  sass_dir: assets
  style: compressed

theme: null

# Daftar plugin yang diizinkan oleh GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

# Hapus bagian "gems" karena sudah tidak digunakan di Jekyll >= 3.5
# Jika Anda menggunakan Jekyll versi baru, cukup gunakan "plugins" di atas
