 title: Home
 baseurl: ""
 url: "https://muhammadalfaraby06.github.io/"

sass:
  sass_dir: assets
  style: compressed

theme : null

# Daftar plugin yang diizinkan oleh GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
  # tambahkan plugin lain yang Anda butuhkan

# Atau jika menggunakan versi Jekyll lama (kurang dari 3.5.0)
gems:
  - jekyll-feed
