title: Home
baseurl: "" # Jangan lupa isi jika repo bukan user/organization site
url: "https://muhammadalfaraby06.github.io"

sass:
  sass_dir: assets/css
  style: compressed
  load_paths:
    - assets/css

theme: null

# Daftar plugin yang diizinkan oleh GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
